# -*- coding: utf-8 -*-
"""palindrome

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBJOTvF_Rt1cQ3xZGNFl7mCJXycsr4bs
"""

def isPalindrome(x):
    if x < 0:
        return False

    original = x
    reverse = 0

    while x > 0:
        digit = x % 10
        reverse = reverse * 10 + digit
        x //= 10

    return original == reverse

x = 121
print(isPalindrome(x))