# -*- coding: utf-8 -*-
"""rev_string

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBJOTvF_Rt1cQ3xZGNFl7mCJXycsr4bs
"""

class Solution:
    def reverseString(self, s):
        left, right = 0, len(s) - 1

        while left < right:
            s[left], s[right] = s[right], s[left]
            left += 1
            right -=1