# -*- coding: utf-8 -*-
"""sum

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBJOTvF_Rt1cQ3xZGNFl7mCJXycsr4bs
"""

def twoSum(nums, target):
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            if nums[i] + nums[j] == target:
                return [i, j]
    return []

# Example
nums = [2, 7, 11, 15]
target = 9

result = twoSum(nums, target)
print(result)